# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'donkey-lock-kit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DonkeyLockKit
  pod 'DonkeyLockKit', '= 1.1.1'
end
